repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: poetry-export-src
        name: poetry export src
        entry: bash -c "cd backend && poetry export -f requirements.txt --output ./src/requirements.txt --without-hashes"
        language: system
        pass_filenames: false
      - id: poetry-export-test
        name: poetry export test
        entry: bash -c "cd backend && poetry export -f requirements.txt --output ./test/requirements.txt --without-hashes --with test"
        language: system
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && npx eslint ."
        language: system
        pass_filenames: false
